/*
 * quant_test.c
 * ============
 * 
 * Test program from the quant module of the Retro synthesizer.
 * 
 * Prints out some data tables generated by the quant module, in order
 * to check that the quant module is producing reasonable results.
 * 
 * Compilation
 * -----------
 * 
 * Compile with the quant module of Retro
 * 
 * May also require the math library to be included with -lm
 */

#include <stdio.h>
#include <stdlib.h>

#include "quant.h"

/*
 * Constants
 * =========
 */

/*
 * The piano key frequencies from Wikipedia, for use in checking the
 * computed frequency table.
 * 
 * Frequencies are stored as strings here.
 * 
 * CAUTION: fractional digits are truncated rather than rounded, so the
 * last digit may be off by one.
 */
static const char *wikiFreq[] = {
  "4186.009",
  "3951.066",
  "3729.310",
  "3520.000",
  "3322.438",
  "3135.963",
  "2959.955",
  "2793.826",
  "2637.020",
  "2489.016",
  "2349.318",
  "2217.461",
  "2093.005",
  "1975.533",
  "1864.655",
  "1760.000",
  "1661.219",
  "1567.982",
  "1479.978",
  "1396.913",
  "1318.510",
  "1244.508",
  "1174.659",
  "1108.731",
  "1046.502",
   "987.766",
   "932.327",
   "880.000",
   "830.609",
   "783.990",
   "739.988",
   "698.456",
   "659.255",
   "622.254",
   "587.329",
   "554.365",
   "523.251",
   "493.883",
   "466.163",
   "440.000",
   "415.304",
   "391.995",
   "369.994",
   "349.228",
   "329.627",
   "311.127",
   "293.664",
   "277.182",
   "261.625",
   "246.941",
   "233.081",
   "220.000",
   "207.652",
   "195.997",
   "184.997",
   "174.614",
   "164.813",
   "155.563",
   "146.832",
   "138.591",
   "130.812",
   "123.470",
   "116.540",
   "110.000",
   "103.826",
    "97.998",
    "92.498",
    "87.307",
    "82.406",
    "77.781",
    "73.416",
    "69.295",
    "65.406",
    "61.735",
    "58.270",
    "55.000",
    "51.913",
    "48.999",
    "46.249",
    "43.653",
    "41.203",
    "38.890",
    "36.708",
    "34.647",
    "32.703",
    "30.867",
    "29.135",
    "27.500"
};

/*
 * The decibels in the Wikipedia table.
 * 
 * Also has a length constant.
 */
#define DB_CHART_LEN (25)
static int16_t db_chart[DB_CHART_LEN] = {
   90,
   80,
   70,
   60,
   50,
   40,
   30,
   20,
   10,
    6,
    3,
    1,
    0,
   -1,
   -3,
   -6,
  -10,
  -20,
  -30,
  -40,
  -50,
  -60,
  -70,
  -80,
  -90
};

/*
 * The Wikipedia amplitude ratio column in the decibels chart.
 * 
 * Entries given as strings.
 */
static const char *wikiDB[DB_CHART_LEN] = {
"31623.        ",
"10000.        ",
" 3162.        ",
" 1000.        ",
"  316.2       ",
"  100.        ",
"   31.62      ",
"   10.        ",
"    3.162     ",
"    1.995     ",
"    1.413     ",
"    1.122     ",
"    1.        ",
"    0.891     ",
"    0.708     ",
"    0.501     ",
"    0.3162    ",
"    0.1000    ",
"    0.03162   ",
"    0.01000   ",
"    0.003162  ",
"    0.001000  ",
"    0.0003162 ",
"    0.0001000 ",
"    0.00003162"
};

/*
 * Local functions
 * ===============
 */

/* Prototypes */
static void pitchTest(void);
static void loudTest(void);
static void stereoTest(void);

/*
 * Test the pitch quantization.
 */
static void pitchTest(void) {
  
  int32_t k = 0;
  int i = 0;
  
  printf("Pitch quantization test\n");
  printf("=======================\n");
  printf("\n");
  printf("Piano key frequencies:\n");
  printf("(Last digit may be off by one due to rounding)\n");
  printf("\n");
  printf(" Generated | Wikipedia\n");
  printf("-----------+-----------\n");
  
  for(k = 4 * 6000;
      k >= (-3 * 6000) + (-3 * 500);
      k -= 500) {
    printf("  %8.3f |  %8s\n", quant_pitch(k), wikiFreq[i]);
    i++;
  }
  
  printf("\n");
  printf("Cents above A-440:\n");
  printf("\n");
  
  for(i = 0; i <= 500; i += 25) {
    printf("%3d cents: %8.3f Hz\n",
              (i / 5),
              quant_pitch((9 * 500) + i));
  }
  
  printf("\n");
}

/*
 * Test the loudness quantization.
 */
static void loudTest(void) {
  
  int i = 0;
  int dc = 0;
  int32_t d = 0;
  
  printf("Decibel quantization test\n");
  printf("=========================\n");
  printf("\n");
  printf("Decibel to multiplier mapping:\n");
  printf("\n");
  printf(" dB  |   Generated    |   Wikipedia\n");
  printf("-----+----------------+----------------\n");
  
  for(i = 0; i < DB_CHART_LEN; i++) {
    /* Get decibels from chart */
    dc = (int) db_chart[i];
    
    /* Convert decibel value to quantized value */
    d = ((int32_t) dc) * 360;
    
    /* Print the row */
    printf(" %3d | %14.8f | %s \n", dc, quant_loud(d), wikiDB[i]);
  }
  
  printf("\n");
}

/*
 * Test the stereo panning quantization,
 */
static void stereoTest(void) {
  
  int32_t p = 0;
  double lc = 0.0;
  double rc = 0.0;
  double fc = 0.0;
  
  printf("Stereo panning quantization test\n");
  printf("================================\n");
  printf("\n");
  
  printf("Panning left to right:\n");
  printf("(Initialized with -3dB center drop)\n");
  printf("\n");
  printf(" Quant. |  Left  | Right  |  Full\n");
  printf("--------+--------+--------+--------\n");
  
  for(p = -32767; p <= 32767; p += 1057) {
    quant_pan(p, &lc, &rc);
    fc = lc + rc;
    printf(" %6d | %.4f | %.4f | %.4f\n", p, lc, rc, fc);
  }
  
  printf("\n");
}

/*
 * Program entrypoint
 * ==================
 */

int main(int argc, char *argv[]) {
  
  int status = 1;
  
  /* Ignore argv parameter */
  (void) argv;
  
  /* Check that no additional arguments */
  if (argc > 1) {
    status = 0;
    fprintf(stderr, "Not expecting any program arguments!\n");
  }
  
  /* Initialize with -3dB center */
  if (status) {
    quant_init(-1080);
  }
  
  /* Perform tests */
  if (status) {
    printf("+=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-+\n");
    printf("|                                      |\n");
    printf("+ R E T R O    Q U A N T I Z A T I O N +\n");
    printf("|                                      |\n");
    printf("+          -- Test program --          +\n");
    printf("|                                      |\n");
    printf("+=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-+\n");
    printf("\n");
    printf("\n");
    
    pitchTest();
    loudTest();
    stereoTest();
  }
  
  /* Invert status and return */
  if (status) {
    status = 0;
  } else {
    status = 1;
  }
  return status;
}
